USE [joshco_pms]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComplaintComment](
	[ComplaintCommentID] [int] IDENTITY(1,1) NOT NULL,
	[ComplaintID] [int] NOT NULL,
	[Comment] [nvarchar](max) NULL,
	[CommentFromUserID] [int] NULL,
	[DateAdded] [datetime] NULL,
 CONSTRAINT [PK_ComplaintComment] PRIMARY KEY CLUSTERED 
(
	[ComplaintCommentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


