ALTER Proc [dbo].[SelectTenantInvoiceList]  -- exec [SelectTenantInvoiceList] 1003, 0, 0

@LeaseID int,
@Mon int,
@Year int

as


Select Result.*
, (Select T.PhysicalAddress+' ,'+cast(T.PhysicalAddressCode as varchar) From [dbo].[Lease]L join [dbo].[Tenant]T on T.TenantID = L.TenantID Where L.LeaseID = Result.LeaseID) as TenantAddress
, (Select T.[Name]+' '+ T.[Surname]  From [dbo].[Lease]L join [dbo].[Tenant]T on T.TenantID = L.TenantID Where L.LeaseID = Result.LeaseID) as TenantName
, (Rent+isnull(AddCost,0))- isnull(Paid,0) as AmountDue

from (
Select [FinYear], 'April' as Mon, 4 as MonNo, [April] as Rent,  [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType,  Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 4)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and  Month(LRP.DueDate) = 4  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear],[April], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'May' as Mon, 5 as MonNo, [May] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 5)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID  and Month(LRP.DueDate) = 5 Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [May], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'June' as Mon, 6 as MonNo, [June] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 6)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID  and Month(LRP.DueDate) = 6  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [June], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'July' as Mon, 7 as MonNo, [July] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 7)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID  and Month(LRP.DueDate) = 7  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [July], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'August' as Mon, 8 as MonNo, [August] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 8)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID  and Month(LRP.DueDate) = 8  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [August], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'September' as Mon, 9 as MonNo, [September] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 9)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID  and Month(LRP.DueDate) = 9  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [September], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'October' as Mon, 10 as MonNo, [October] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 10)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and Month(LRP.DueDate) = 10  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [October], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'November' as Mon, 11 as MonNo, [November] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 11)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and Month(LRP.DueDate) = 11  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [November], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'December' as Mon, 12 as MonNo, [December] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 12)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and  Month(LRP.DueDate) = 12  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())+1 GROUP BY  LRP.LeaseRentID, [FinYear], [December], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'January' as Mon, 1 as MonNo, [January] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 1)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and  Month(LRP.DueDate) = 1  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())-1 GROUP BY  LRP.LeaseRentID, [FinYear], [January], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'February' as Mon, 2 as MonNo, [February] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 2)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and Month(LRP.DueDate) = 2  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())-1 GROUP BY  LRP.LeaseRentID, [FinYear], [February], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
union all Select [FinYear], 'March' as Mon, 3 as MonNo, [March] as Rent, [Amount] as AddCost, isnull(LC.LeaseCostTypeOther,'') as AddCostType, Sum(AmountPaid) as Paid, LR.[LeaseID], LRP.DueDate FROM  [dbo].[LeaseRent]LR left join [dbo].[LeaseAdditionalCost]LC on LR.LeaseID = LC.LeaseID  and ((LC.Monthy = 1) or (LC.Monthy = 0 and year(LC.StartDate) = LR.FinYear and Month(LC.StartDate) = 3)) left join [dbo].[LeaseRentPaid]LRP on LR.LeaseRentID = LRP.LeaseRentID and  Month(LRP.DueDate) = 3  Where LR.LeaseID = @LeaseID and FinYear <= Year(GetDate())-1 GROUP BY  LRP.LeaseRentID, [FinYear], [March], [Amount], LC.LeaseCostTypeOther,LR.[LeaseID], LRP.DueDate
) as Result 
Where (MonNo = @Mon or @Mon = 0)
and (Cast([FinYear] as int) = @Year or @Year =0)
and((Cast([FinYear] as int) = Year(Getdate())+1 and MonNo <= Month(Getdate()))
or Cast([FinYear] as int) < Year(Getdate()))
and Rent is not null
Order by FinYear Desc, MonNo Desc
