
CREATE TABLE [dbo].[Student_Accommodation_Unit](
	[UNITID] [int] IDENTITY(1,1) NOT NULL,
	[UNIT_NUMBER] [nvarchar](10) NULL,
	[UNIT_TYPE] [nvarchar](100) NULL,
	[ROOM_SHARING_QTY] [int] NULL,
	[RATE] [nvarchar](10) NULL,
	[FLOOR] [int] NULL,
	[RENTAL_AMOUNT] [decimal](18, 2) NULL,
 CONSTRAINT [PK_StudentAccommodationUnity] PRIMARY KEY CLUSTERED 
(
	[UNITID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO