//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joshcoWA.External.TpnSecurityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityInfo", Namespace="http://tpn.co.za/")]
    [System.SerializableAttribute()]
    public partial class SecurityInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthToken {
            get {
                return this.AuthTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthTokenField, value) != true)) {
                    this.AuthTokenField = value;
                    this.RaisePropertyChanged("AuthToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OutputFormat {
            get {
                return this.OutputFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputFormatField, value) != true)) {
                    this.OutputFormatField = value;
                    this.RaisePropertyChanged("OutputFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LoginCode {
            get {
                return this.LoginCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginCodeField, value) != true)) {
                    this.LoginCodeField = value;
                    this.RaisePropertyChanged("LoginCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tpn.co.za/", ConfigurationName="TpnSecurityService.SecuritySoap")]
    public interface SecuritySoap {
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/Validate", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.ValidateResponse Validate(joshcoWA.External.TpnSecurityService.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.ValidateResponse> ValidateAsync(joshcoWA.External.TpnSecurityService.ValidateRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GenerateAuthToken", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse GenerateAuthToken(joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GenerateAuthToken", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse> GenerateAuthTokenAsync(joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgencyCode", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse GetAgencyCode(joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgencyCode", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse> GetAgencyCodeAsync(joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgentDetails", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse GetAgentDetails(joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse> GetAgentDetailsAsync(joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgentContactDetails", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse GetAgentContactDetails(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/GetAgentContactDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse> GetAgentContactDetailsAsync(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityBlock from namespace http://tpn.co.za/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/DecodeEncryptedString", ReplyAction="*")]
        joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse DecodeEncryptedString(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tpn.co.za/DecodeEncryptedString", ReplyAction="*")]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse> DecodeEncryptedStringAsync(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(joshcoWA.External.TpnSecurityService.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            this.SecurityBlock = SecurityBlock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(joshcoWA.External.TpnSecurityService.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(System.Xml.Linq.XElement ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAuthTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAuthToken", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequestBody Body;
        
        public GenerateAuthTokenRequest() {
        }
        
        public GenerateAuthTokenRequest(joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GenerateAuthTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        public GenerateAuthTokenRequestBody() {
        }
        
        public GenerateAuthTokenRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            this.SecurityBlock = SecurityBlock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAuthTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAuthTokenResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponseBody Body;
        
        public GenerateAuthTokenResponse() {
        }
        
        public GenerateAuthTokenResponse(joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GenerateAuthTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GenerateAuthTokenResult;
        
        public GenerateAuthTokenResponseBody() {
        }
        
        public GenerateAuthTokenResponseBody(System.Xml.Linq.XElement GenerateAuthTokenResult) {
            this.GenerateAuthTokenResult = GenerateAuthTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgencyCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgencyCode", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgencyCodeRequestBody Body;
        
        public GetAgencyCodeRequest() {
        }
        
        public GetAgencyCodeRequest(joshcoWA.External.TpnSecurityService.GetAgencyCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgencyCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        public GetAgencyCodeRequestBody() {
        }
        
        public GetAgencyCodeRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            this.SecurityBlock = SecurityBlock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgencyCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgencyCodeResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgencyCodeResponseBody Body;
        
        public GetAgencyCodeResponse() {
        }
        
        public GetAgencyCodeResponse(joshcoWA.External.TpnSecurityService.GetAgencyCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgencyCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAgencyCodeResult;
        
        public GetAgencyCodeResponseBody() {
        }
        
        public GetAgencyCodeResponseBody(System.Xml.Linq.XElement GetAgencyCodeResult) {
            this.GetAgencyCodeResult = GetAgencyCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgentDetails", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgentDetailsRequestBody Body;
        
        public GetAgentDetailsRequest() {
        }
        
        public GetAgentDetailsRequest(joshcoWA.External.TpnSecurityService.GetAgentDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgentDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        public GetAgentDetailsRequestBody() {
        }
        
        public GetAgentDetailsRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            this.SecurityBlock = SecurityBlock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgentDetailsResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgentDetailsResponseBody Body;
        
        public GetAgentDetailsResponse() {
        }
        
        public GetAgentDetailsResponse(joshcoWA.External.TpnSecurityService.GetAgentDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgentDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAgentDetailsResult;
        
        public GetAgentDetailsResponseBody() {
        }
        
        public GetAgentDetailsResponseBody(System.Xml.Linq.XElement GetAgentDetailsResult) {
            this.GetAgentDetailsResult = GetAgentDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentContactDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgentContactDetails", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequestBody Body;
        
        public GetAgentContactDetailsRequest() {
        }
        
        public GetAgentContactDetailsRequest(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgentContactDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        public GetAgentContactDetailsRequestBody() {
        }
        
        public GetAgentContactDetailsRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            this.SecurityBlock = SecurityBlock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentContactDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgentContactDetailsResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponseBody Body;
        
        public GetAgentContactDetailsResponse() {
        }
        
        public GetAgentContactDetailsResponse(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class GetAgentContactDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAgentContactDetailsResult;
        
        public GetAgentContactDetailsResponseBody() {
        }
        
        public GetAgentContactDetailsResponseBody(System.Xml.Linq.XElement GetAgentContactDetailsResult) {
            this.GetAgentContactDetailsResult = GetAgentContactDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecodeEncryptedStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecodeEncryptedString", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequestBody Body;
        
        public DecodeEncryptedStringRequest() {
        }
        
        public DecodeEncryptedStringRequest(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class DecodeEncryptedStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedString;
        
        public DecodeEncryptedStringRequestBody() {
        }
        
        public DecodeEncryptedStringRequestBody(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock, string encryptedString) {
            this.SecurityBlock = SecurityBlock;
            this.encryptedString = encryptedString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecodeEncryptedStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecodeEncryptedStringResponse", Namespace="http://tpn.co.za/", Order=0)]
        public joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponseBody Body;
        
        public DecodeEncryptedStringResponse() {
        }
        
        public DecodeEncryptedStringResponse(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tpn.co.za/")]
    public partial class DecodeEncryptedStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DecodeEncryptedStringResult;
        
        public DecodeEncryptedStringResponseBody() {
        }
        
        public DecodeEncryptedStringResponseBody(System.Xml.Linq.XElement DecodeEncryptedStringResult) {
            this.DecodeEncryptedStringResult = DecodeEncryptedStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecuritySoapChannel : joshcoWA.External.TpnSecurityService.SecuritySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuritySoapClient : System.ServiceModel.ClientBase<joshcoWA.External.TpnSecurityService.SecuritySoap>, joshcoWA.External.TpnSecurityService.SecuritySoap {
        
        public SecuritySoapClient() {
        }
        
        public SecuritySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.ValidateResponse joshcoWA.External.TpnSecurityService.SecuritySoap.Validate(joshcoWA.External.TpnSecurityService.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public System.Xml.Linq.XElement Validate(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.ValidateRequest inValue = new joshcoWA.External.TpnSecurityService.ValidateRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.ValidateRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            joshcoWA.External.TpnSecurityService.ValidateResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.ValidateResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.ValidateAsync(joshcoWA.External.TpnSecurityService.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.ValidateResponse> ValidateAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.ValidateRequest inValue = new joshcoWA.External.TpnSecurityService.ValidateRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.ValidateRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).ValidateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse joshcoWA.External.TpnSecurityService.SecuritySoap.GenerateAuthToken(joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest request) {
            return base.Channel.GenerateAuthToken(request);
        }
        
        public System.Xml.Linq.XElement GenerateAuthToken(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest inValue = new joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GenerateAuthToken(inValue);
            return retVal.Body.GenerateAuthTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.GenerateAuthTokenAsync(joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest request) {
            return base.Channel.GenerateAuthTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GenerateAuthTokenResponse> GenerateAuthTokenAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest inValue = new joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GenerateAuthTokenRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GenerateAuthTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgencyCode(joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest request) {
            return base.Channel.GetAgencyCode(request);
        }
        
        public System.Xml.Linq.XElement GetAgencyCode(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgencyCodeRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgencyCode(inValue);
            return retVal.Body.GetAgencyCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgencyCodeAsync(joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest request) {
            return base.Channel.GetAgencyCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgencyCodeResponse> GetAgencyCodeAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgencyCodeRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgencyCodeRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgencyCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgentDetails(joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest request) {
            return base.Channel.GetAgentDetails(request);
        }
        
        public System.Xml.Linq.XElement GetAgentDetails(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgentDetailsRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgentDetails(inValue);
            return retVal.Body.GetAgentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgentDetailsAsync(joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest request) {
            return base.Channel.GetAgentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentDetailsResponse> GetAgentDetailsAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgentDetailsRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgentDetailsRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgentDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgentContactDetails(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest request) {
            return base.Channel.GetAgentContactDetails(request);
        }
        
        public System.Xml.Linq.XElement GetAgentContactDetails(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgentContactDetails(inValue);
            return retVal.Body.GetAgentContactDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.GetAgentContactDetailsAsync(joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest request) {
            return base.Channel.GetAgentContactDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.GetAgentContactDetailsResponse> GetAgentContactDetailsAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock) {
            joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest inValue = new joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.GetAgentContactDetailsRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).GetAgentContactDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse joshcoWA.External.TpnSecurityService.SecuritySoap.DecodeEncryptedString(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest request) {
            return base.Channel.DecodeEncryptedString(request);
        }
        
        public System.Xml.Linq.XElement DecodeEncryptedString(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock, string encryptedString) {
            joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest inValue = new joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            inValue.Body.encryptedString = encryptedString;
            joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse retVal = ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).DecodeEncryptedString(inValue);
            return retVal.Body.DecodeEncryptedStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse> joshcoWA.External.TpnSecurityService.SecuritySoap.DecodeEncryptedStringAsync(joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest request) {
            return base.Channel.DecodeEncryptedStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<joshcoWA.External.TpnSecurityService.DecodeEncryptedStringResponse> DecodeEncryptedStringAsync(joshcoWA.External.TpnSecurityService.SecurityInfo SecurityBlock, string encryptedString) {
            joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest inValue = new joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequest();
            inValue.Body = new joshcoWA.External.TpnSecurityService.DecodeEncryptedStringRequestBody();
            inValue.Body.SecurityBlock = SecurityBlock;
            inValue.Body.encryptedString = encryptedString;
            return ((joshcoWA.External.TpnSecurityService.SecuritySoap)(this)).DecodeEncryptedStringAsync(inValue);
        }
    }
}
